<?php
/**
 * Provincias por código INE. Los dos primeros dígitos del código postal
 * coinciden con este código, así que el CP basta para saber la provincia.
 */
return [
    '01' => ['nombre' => 'Araba/Álava', 'slug' => 'alava', 'ccaa' => 'País Vasco'],
    '02' => ['nombre' => 'Albacete', 'slug' => 'albacete', 'ccaa' => 'Castilla-La Mancha'],
    '03' => ['nombre' => 'Alicante/Alacant', 'slug' => 'alicante', 'ccaa' => 'Comunitat Valenciana'],
    '04' => ['nombre' => 'Almería', 'slug' => 'almeria', 'ccaa' => 'Andalucía'],
    '05' => ['nombre' => 'Ávila', 'slug' => 'avila', 'ccaa' => 'Castilla y León'],
    '06' => ['nombre' => 'Badajoz', 'slug' => 'badajoz', 'ccaa' => 'Extremadura'],
    '07' => ['nombre' => 'Illes Balears', 'slug' => 'baleares', 'ccaa' => 'Illes Balears'],
    '08' => ['nombre' => 'Barcelona', 'slug' => 'barcelona', 'ccaa' => 'Cataluña'],
    '09' => ['nombre' => 'Burgos', 'slug' => 'burgos', 'ccaa' => 'Castilla y León'],
    '10' => ['nombre' => 'Cáceres', 'slug' => 'caceres', 'ccaa' => 'Extremadura'],
    '11' => ['nombre' => 'Cádiz', 'slug' => 'cadiz', 'ccaa' => 'Andalucía'],
    '12' => ['nombre' => 'Castellón/Castelló', 'slug' => 'castellon', 'ccaa' => 'Comunitat Valenciana'],
    '13' => ['nombre' => 'Ciudad Real', 'slug' => 'ciudad-real', 'ccaa' => 'Castilla-La Mancha'],
    '14' => ['nombre' => 'Córdoba', 'slug' => 'cordoba', 'ccaa' => 'Andalucía'],
    '15' => ['nombre' => 'A Coruña', 'slug' => 'a-coruna', 'ccaa' => 'Galicia'],
    '16' => ['nombre' => 'Cuenca', 'slug' => 'cuenca', 'ccaa' => 'Castilla-La Mancha'],
    '17' => ['nombre' => 'Girona', 'slug' => 'girona', 'ccaa' => 'Cataluña'],
    '18' => ['nombre' => 'Granada', 'slug' => 'granada', 'ccaa' => 'Andalucía'],
    '19' => ['nombre' => 'Guadalajara', 'slug' => 'guadalajara', 'ccaa' => 'Castilla-La Mancha'],
    '20' => ['nombre' => 'Gipuzkoa', 'slug' => 'gipuzkoa', 'ccaa' => 'País Vasco'],
    '21' => ['nombre' => 'Huelva', 'slug' => 'huelva', 'ccaa' => 'Andalucía'],
    '22' => ['nombre' => 'Huesca', 'slug' => 'huesca', 'ccaa' => 'Aragón'],
    '23' => ['nombre' => 'Jaén', 'slug' => 'jaen', 'ccaa' => 'Andalucía'],
    '24' => ['nombre' => 'León', 'slug' => 'leon', 'ccaa' => 'Castilla y León'],
    '25' => ['nombre' => 'Lleida', 'slug' => 'lleida', 'ccaa' => 'Cataluña'],
    '26' => ['nombre' => 'La Rioja', 'slug' => 'la-rioja', 'ccaa' => 'La Rioja'],
    '27' => ['nombre' => 'Lugo', 'slug' => 'lugo', 'ccaa' => 'Galicia'],
    '28' => ['nombre' => 'Madrid', 'slug' => 'madrid', 'ccaa' => 'Comunidad de Madrid'],
    '29' => ['nombre' => 'Málaga', 'slug' => 'malaga', 'ccaa' => 'Andalucía'],
    '30' => ['nombre' => 'Murcia', 'slug' => 'murcia', 'ccaa' => 'Región de Murcia'],
    '31' => ['nombre' => 'Navarra', 'slug' => 'navarra', 'ccaa' => 'Navarra'],
    '32' => ['nombre' => 'Ourense', 'slug' => 'ourense', 'ccaa' => 'Galicia'],
    '33' => ['nombre' => 'Asturias', 'slug' => 'asturias', 'ccaa' => 'Asturias'],
    '34' => ['nombre' => 'Palencia', 'slug' => 'palencia', 'ccaa' => 'Castilla y León'],
    '35' => ['nombre' => 'Las Palmas', 'slug' => 'las-palmas', 'ccaa' => 'Canarias'],
    '36' => ['nombre' => 'Pontevedra', 'slug' => 'pontevedra', 'ccaa' => 'Galicia'],
    '37' => ['nombre' => 'Salamanca', 'slug' => 'salamanca', 'ccaa' => 'Castilla y León'],
    '38' => ['nombre' => 'Santa Cruz de Tenerife', 'slug' => 'santa-cruz-de-tenerife', 'ccaa' => 'Canarias'],
    '39' => ['nombre' => 'Cantabria', 'slug' => 'cantabria', 'ccaa' => 'Cantabria'],
    '40' => ['nombre' => 'Segovia', 'slug' => 'segovia', 'ccaa' => 'Castilla y León'],
    '41' => ['nombre' => 'Sevilla', 'slug' => 'sevilla', 'ccaa' => 'Andalucía'],
    '42' => ['nombre' => 'Soria', 'slug' => 'soria', 'ccaa' => 'Castilla y León'],
    '43' => ['nombre' => 'Tarragona', 'slug' => 'tarragona', 'ccaa' => 'Cataluña'],
    '44' => ['nombre' => 'Teruel', 'slug' => 'teruel', 'ccaa' => 'Aragón'],
    '45' => ['nombre' => 'Toledo', 'slug' => 'toledo', 'ccaa' => 'Castilla-La Mancha'],
    '46' => ['nombre' => 'Valencia/València', 'slug' => 'valencia', 'ccaa' => 'Comunitat Valenciana'],
    '47' => ['nombre' => 'Valladolid', 'slug' => 'valladolid', 'ccaa' => 'Castilla y León'],
    '48' => ['nombre' => 'Bizkaia', 'slug' => 'bizkaia', 'ccaa' => 'País Vasco'],
    '49' => ['nombre' => 'Zamora', 'slug' => 'zamora', 'ccaa' => 'Castilla y León'],
    '50' => ['nombre' => 'Zaragoza', 'slug' => 'zaragoza', 'ccaa' => 'Aragón'],
    '51' => ['nombre' => 'Ceuta', 'slug' => 'ceuta', 'ccaa' => 'Ceuta'],
    '52' => ['nombre' => 'Melilla', 'slug' => 'melilla', 'ccaa' => 'Melilla'],
];
